### ISSUE TITLE
Stuck at: ` [custom-init] No custom files found, skipping...`

### ISSUE THREAD

**Issue by MikeChongCan** [105PM/docker-warp#5]
```yaml
version: "3"
services:
  warproxy:
    container_name: docker-warproxy
    image: ghcr.io/105pm/docker-warproxy:latest
    network_mode: bridge
    restart: always
    volumes:
      - ./data/config:/config
    ports:
      - 28008:${PROXY_PORT:-8008}
        #      - 28080:8080
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - WARP_PLUS=true
      - WGCF_LICENSE_KEY=
      - WGCF_DEVICE_NAME=
      - PROXY_USER=
      - PROXY_PASS=
```

Full log:

```
docker-warproxy  | [migrations] started
docker-warproxy  | [migrations] no migrations found
docker-warproxy  | usermod: no changes
docker-warproxy  | ───────────────────────────────────────
docker-warproxy  |   _____ __ __ _____ _____ _____ _____
docker-warproxy  |  |     |  |  |   __|_   _|     |     |
docker-warproxy  |  |   --|  |  |__   | | | |  |  | | | |
docker-warproxy  |  |_____|_____|_____| |_| |_____|_|_|_|
docker-warproxy  |        _____ __ __ _ __    ____
docker-warproxy  |       | __  |  |  | |  |  |    \
docker-warproxy  |       | __ -|  |  | |  |__|  |  |
docker-warproxy  |       |_____|_____|_|_____|____/
docker-warproxy  |
docker-warproxy  |   Based on images from linuxserver.io
docker-warproxy  | ───────────────────────────────────────
docker-warproxy  |
docker-warproxy  | To support LSIO projects visit:
docker-warproxy  | https://www.linuxserver.io/donate/
docker-warproxy  |
docker-warproxy  | ───────────────────────────────────────
docker-warproxy  | GID/UID
docker-warproxy  | ───────────────────────────────────────
docker-warproxy  |
docker-warproxy  | User UID:    911
docker-warproxy  | User GID:    911
docker-warproxy  | ───────────────────────────────────────
docker-warproxy  |
docker-warproxy  | *** wgcf: Updating account info...
docker-warproxy  | [timestamp] Using config file: /config/wgcf-account.toml
docker-warproxy  | [timestamp] =======================================
docker-warproxy  | [timestamp] Device name   : phoneix
docker-warproxy  | [timestamp] Device model  : PC
docker-warproxy  | [timestamp] Device active : true
docker-warproxy  | [timestamp] Account type  : limited
docker-warproxy  | [timestamp] Role          : child
docker-warproxy  | [timestamp] Premium data  : 21.85 PiB
docker-warproxy  | [timestamp] Quota         : 21.85 PiB
docker-warproxy  | [timestamp] =======================================
docker-warproxy  | [timestamp] Successfully updated Cloudflare Warp account
docker-warproxy  | [custom-init] No custom files found, skipping...
```
